shopping_list=["milk","bread", "pastry"]
print(shopping_list)
print(type(shopping_list))
print(len(shopping_list))
print(shopping_list[2])
shopping_list.append ("poha")
print(shopping_list)
shopping_list.insert (4,"halwa")
print(shopping_list)
shopping_list.remove("poha")
print(shopping_list)
shopping_list.pop()
print(shopping_list)
shopping_list.reverse()
print(shopping_list)
shopping_list.sort()
print(shopping_list)
shopping_list.extend(["poha", "halwa"])
print(shopping_list)